apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tqnszqvzk-python 
  janus-idp.io/tekton: tqnszqvzk-python
  backstage.io/kubernetes-id: tqnszqvzk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tqnszqvzk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  